reformat SNIfinder file

diff --git a/SNIfinder b/SNIfinder
--- a/SNIfinder
+++ b/SNIfinder
@@ -14,45 +14,45 @@ file_path="$script_dir/$filename"
 # URL="https://asriran.com"
 
 OPTION=$(whiptail --title "Menu" --menu "Select an option:" 10 40 4 \
-	"1" "Custom selection" \
-	"2" "Random selection" \
-	"3" "Exit" \
-	3>&1 1>&2 2>&3)
+"1" "Custom selection" \
+"2" "Random selection" \
+"3" "Exit" \
+3>&1 1>&2 2>&3)
 
 exitstatus=$?
 if [ $exitstatus = 0 ]; then
-	    if [ $OPTION == 1 ]; then
-		            echo "Your chosen option: 1"
-			            URL=$(whiptail --title "Test Free-form Input Box" --inputbox "Enter your URL" 10 60 3>&1 1>&2 2>&3)
-				            response=$(curl --tlsv1.3 -I https://"$URL" 2>/dev/null)
+    if [ $OPTION == 1 ]; then
+        echo "Your chosen option: 1"
+        URL=$(whiptail --title "Test Free-form Input Box" --inputbox "Enter your URL" 10 60 3>&1 1>&2 2>&3)
+        response=$(curl --tlsv1.3 -I https://"$URL" 2>/dev/null)
 
-					            # Check if the response headers indicate TLS 1.3
-						            if [[ $response == *"HTTP/2"* ]]; then
-								                whiptail --title "Result" --msgbox "TLS 1.3 is supported for $URL" 10 60
-										        else
-												            whiptail --title "Result" --msgbox "TLS 1.3 is supported for $URL" 10 60
-													            fi
-														        fi
-															    if [ $OPTION == 2 ]; then
-																            # Check if the file exists
-																	            if [ ! -f "$file_path" ]; then
-																			                echo "File not found: $file_path"
-																					            exit 1
-																						            fi
-																							            # Get a random line from the file
-																								            random_line=$(shuf -n 1 "$file_path")
-																									            response=$(curl --tlsv1.3 -I https://"$random_line" 2>/dev/null)
-																										            # Check if the response headers indicate TLS 1.3
-																											            if [[ $response == *"HTTP/2"* ]]; then
-																													                whiptail --title "Result" --msgbox "TLS 1.3 is supported for $random_line" 10 60
-																															        else
-																																	            whiptail --title "Result" --msgbox "TLS 1.3 is supported for $random_line" 10 60
-																																		            fi
-																																			            # echo "Your chosen option: 2"
-																																				        fi
-																																					    if [ $OPTION == 3 ]; then
-																																						            exit 1
-																																							        fi
-																																							else
-																																								    exit 1
+        # Check if the response headers indicate TLS 1.3
+        if [[ $response == *"HTTP/2"* ]]; then
+            whiptail --title "Result" --msgbox "TLS 1.3 is supported for $URL" 10 60
+        else
+            whiptail --title "Result" --msgbox "TLS 1.3 is supported for $URL" 10 60
+        fi
+    fi
+    if [ $OPTION == 2 ]; then
+        # Check if the file exists
+        if [ ! -f "$file_path" ]; then
+            echo "File not found: $file_path"
+            exit 1
+        fi
+        # Get a random line from the file
+        random_line=$(shuf -n 1 "$file_path")
+        response=$(curl --tlsv1.3 -I https://"$random_line" 2>/dev/null)
+        # Check if the response headers indicate TLS 1.3
+        if [[ $response == *"HTTP/2"* ]]; then
+            whiptail --title "Result" --msgbox "TLS 1.3 is supported for $random_line" 10 60
+        else
+            whiptail --title "Result" --msgbox "TLS 1.3 is supported for $random_line" 10 60
+        fi
+        # echo "Your chosen option: 2"
+    fi
+    if [ $OPTION == 3 ]; then
+        exit 1
+    fi
+else
+    exit 1
 fi
